lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # para versiones < 2.6
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'tu_contraseña_segura'
    token_ttl: 3600
