
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
