# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Controladores
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # Servicios de aplicación
  App\Service\:
    resource: '../src/Service'

  # Repositorios Doctrine como servicios
  App\Repository\:
    resource: '../src/Repository'
    tags: ['doctrine.repository_service']
